name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Setup Luajit
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Golnag
        run: |
          go version
          export CGO_ENABLED=0
          go build
      - name: Build Luajit
        run: |
          luajit -v
          folder="./script"
          for file in $folder/*.lua
          do
            luajit -b $file $file
          done
      - name: Archive Files
        run: |
          tar -czvf wafcdn.tar.gz wafcdn .env.sample conf script
          zip -r wafcdn.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wafcdn.tar.gz
            wafcdn.zip
