name: release

on:
  push:
    branches: 
      - main

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        with:
          repository: 'penndev/veadmin'
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: Build
        run: | 
          npm install
          npm run build:wafcdn
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./dist # 部署编译后的文件
  bin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        with:
          repository: 'penndev/galite'
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: latest
      - name: Build
        run: go build -o wafcdn ./cmd/wafcdn/main.go
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./wafcdn # 部署编译后的文件
  wafcdn:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Luajit Setup
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "luajit-openresty"
      - name: Build
        run: |
          luajit -v
          for file in ./script/*.lua
          do
            luajit -b $file $file
          done
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./script
