name: release

on:
  push:
    branches: 
      - main

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        with:
          repository: 'penndev/veadmin'
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: Build
        run: | 
          npm install
          npm run build:wafcdn
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            ./dist
  bin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4
        with:
          repository: 'penndev/galite'
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Build
        run: go build -o wafcdn ./cmd/wafcdn/main.go
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: ./wafcdn # 部署编译后的文件
  script:
    runs-on: ubuntu-latest
    container:
      image: openresty/openresty
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          /usr/local/openresty/luajit/bin/luajit -v
          for file in ./script/*.lua
          do
            /usr/local/openresty/luajit/bin/luajit -b "$file" "$file"
          done
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: script
          path: |
            ./script
            ./conf
            ./Dockerfile
            ./README.md
  docker:
    runs-on: ubuntu-latest
    needs:
      - dist
      - bin
      - script
    steps:
      - name: Download Dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Download Bin
        uses: actions/download-artifact@v4
        with:
          name: bin
          path: ./
      - name: Download Script
        uses: actions/download-artifact@v4
        with:
          name: script
          path: ./
      - name: Ls File
        run: |
          chmod +x ./wafcdn
          ls -al
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: penndev
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: penndev/wafcdn:latest
